### ISSUE TITLE
Module not loading?

### ISSUE THREAD

**Issue by jpringle03** [manifestinteractive/MMM-Nest-Camera#1]
Hey there!

Thanks for making this Magic Mirror module! I tried to set it up last night but I can't seem to get anything to display. I'm familiar with the Nest Developer console as I've used it for https://github.com/jclarke0000/MMM-MyNest module and HomeBridge.

When I start up Magic Mirror I see the Nest house icon for a few seconds and then it just disappears and nothing replaces it. I was wondering if there is any debugging you could recommend?

My config currently looks like this:

```
{
				module: "MMM-Nest-Camera",
				position: "lower_third",
				config: {
					size: 'small',
					mode: 'video',
        			        whereFilter: ['Front Door'],
					token: "XXX"  }
			  },
```

I also attempted removing the `whereFilter` but same results every time.

**Comment by lgreerduo** [comment]
I can confirm, this module isn't loading for me either. It seems to load as the Nest logo shows for a hot second but nothing is shown once everything else also loads.

**Comment by poonasor** [comment]
you are missing the token in the config

**Comment by jpringle03** [comment]
This was because the camera was not shared publicly. I just put up a pull request to update the README and fix something else.

Thanks!
